### ISSUE TITLE
globalOption undefined

### ISSUE THREAD

**Issue by YonChun** [cutting-mat/uploader#1]
报错信息：
<img width="766" alt="image" src="https://user-images.githubusercontent.com/27072445/187384496-3f9628c0-b839-43c7-a536-9f4edbb6b43f.png">
调试断点：
<img width="988" alt="image" src="https://user-images.githubusercontent.com/27072445/187384716-356fd146-1f7c-419c-9bb3-6daebf19ef2f.png">
main.js 引入组件:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/27072445/187385738-d645e7fa-4255-4b7c-a66e-9fcdea0379eb.png">
upload.config.js:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/27072445/187385846-62e7a2a4-d62e-4e46-b4ce-ad4a85a11572.png">
config对象输出：
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/27072445/187384858-ac9d2568-408e-411a-b465-0f708c5659b9.png">

直接使用源码到项目中可以正常使用。
源码运行也能正常使用。
是我引入的方法有问题吗

**Comment by tower1229** [comment]
应该是吧，https://github.com/cutting-mat/cutting-mat-admin 这个项目里也用的这个上传插件，你可以自己对比下
